CREATE TABLE APP_USER (
    AU_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    AU_CREATE_DATE datetime NOT NULL,
    AU_EMPLOYEE_ID varchar(255) DEFAULT NULL,
    AU_FIRST_NAME varchar(255) DEFAULT NULL,
    AU_LAST_NAME varchar(255) DEFAULT NULL,
    AU_STATUS varchar(255) NOT NULL,
    AU_USERNAME varchar(255) NOT NULL UNIQUE,
    AU_PASSWORD varchar(255) NOT NULL,
    AU_EMAIL varchar(255) DEFAULT NULL,
    AU_DEPARTMENT varchar(255) DEFAULT NULL,
    AU_PHONE varchar(255) DEFAULT NULL,
    AU_LEVEL varchar(255) NOT NULL
);

CREATE TABLE USER_LOG (
    LOG_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOG_CREATE_DATE datetime NOT NULL,
    LOG_STATUS varchar(255) NOT NULL,
    LOG_IP varchar(255) NOT NULL,
    LOG_AU INTEGER NOT NULL
);